Add command option `regional_names` to `plot_growth_rate`
IslasGECI/population_trend pull request #1
Opened 2024-10-23 19:11 UTC by Chio360

- Added command option `regional_names` to `plot_growth_rate` 
- Added argument `regional_names` to class `Plotter_groth_rate`
- Fix mutmut version

2024-10-24 18:55 UTC, nepito requested changes

2024-10-24 18:55 UTC, nepito commented on population_trend/__init__.py
> +__version__ = "6.0.0"
Por favor sube el número menor y no el mayor.

Hoy revisamos que nadie usa la clase `Plotter_Growth_Rate()`. Esta clase es la que tronaba con las pruebas viejas. Así que no será necesario subir el número mayor.
```suggestion
__version__ = "5.10.0"
```

2024-10-25 15:27 UTC, mvillasante commented on Dockerfile
> +    mutmut==2.4.0 \
Ayer fijamos la versión 2.5.1 porque fue la que nos sirvió

2024-10-25 16:30 UTC, devarops commented on CHANGELOG.md
> +## [6.0.0] - 2024-10-23
¿Será 5.10.0 o 6.0.0?

```suggestion
## [5.10.0] - 2024-10-23
```

2024-10-25 16:32 UTC, devarops commented on tests/test_cli.py
> +    assert obtained==expected
Falta fin de línea.

2024-10-25 16:47 UTC, devarops requested changes
Hola @Chio360:

Felicidades por tu primer _pull request_ (PR). Por favor atiende los comentarios que te dejamos y solicita revisión nuevamente.

- [ ] **Comments**: Are the comments clear and useful?
- [x] **Complexity**: Could the code be made simpler? Would another developer be able to easily understand and use this code when they come across it in the future?
- [x] **Design**: Is the code well-designed and appropriate for your system?
- [ ] **Documentation**: Did the developer also update relevant documentation?
    - [ ] Actualizar CHANGELOG
    - [ ] ¿Podemos agregar _docstrings_ a `obtain_name_from_regional_names()`?
- [x] **Functionality**: Does the code behave as the author likely intended? Is the way the code behaves good for its users?
- [x] **Interface**: Any interface changes are sensible and look good.
- [ ] **Naming**: Did the developer choose clear names for variables, classes, methods, etc.?
    - [ ] ¿Cuál es la diferencia entre ` lambdas_dict` y `lambdas_dict_2`?
- [x] **Style**: Does the code follow our style guides?
- [x] **Tests**: Does the code have correct and well-designed automated tests?
- [x] **YAGNI**: The developer is not implementing things they might need in the future but don’t know they need now.

2024-10-25 16:49 UTC, devarops commented
@Chio360: Por favor podrías resolver los conflictos necesarios para hacer _merge_, atender los cometarios que te dejamos y solicitar revisión nuevamente?

2024-10-25 17:17 UTC, Chio360 commented on tests/test_cli.py
> +    assert obtained==expected
Resuelto

2024-10-25 17:52 UTC, Chio360 commented on Dockerfile
> +    mutmut==2.4.0 \
Hecho

2024-12-01 19:15 UTC, devarops commented
@nepito:
¿Qué hace falta para aceptar o rechazar este PR?

2024-12-02 17:31 UTC, nepito commented
> @nepito: ¿Qué hace falta para aceptar o rechazar este PR?

@devarops Hay algunos conflictos. Yo creo que si atendemos esos conflictos ya podríamos cerrar este _pr_.

2025-01-17 22:51 UTC, devarops commented
@nepito: 
¿Podríamos eliminar este PR por favor?

2025-01-22 00:10 UTC, closed without merging